version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db

  db:
    image: subriais/shopping_list_db:1.0.0
    container_name: mysql_remote
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopping_list_db
    ports:
      - "3306:3306"
    hostname: mysql-db
    volumes:
      - db_data:/var/lib/mysql  # Define the volume for persistence

volumes:
  db_data:
    driver: local  # This uses a local volume driver
