version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      DB_HOST: db  # Use 'db' as the hostname
    networks:
      - app_network

  db:
    image: subriais/shopping_list_db:1.0.0
    container_name: mysql_remote
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopping_list_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
