name: Maven Build and Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: subriais/shopping_list_db:1.0.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: shopping_list_db
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'  # Can also use 'zulu' or 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/mvnw') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile the project
        run: mvn clean compile --offline

      - name: Run tests
        run: mvn test --offline

      - name: Package the project
        run: mvn package --offline

      - name: Create a timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Publish package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: shopping-list-backend-${{ env.TIMESTAMP }}
          path: target/*.jar
