name: Maven Build and Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: subriais/shopping_list_db:1.0.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: shopping_list_db
        ports:
          - "3306:3306"  # This is necessary to expose the port to the job environment
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Updated to the latest version of checkout

      - name: Set up JDK
        uses: actions/setup-java@v3  # Updated to the latest version of setup-java
        with:
          java-version: '18'  # Specify Java 18
          distribution: 'adopt'  # You can also use 'zulu' or 'temurin'

      - name: Package the project
        run: mvn clean package

      - name: Create a timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Publish package as artifact
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: shopping-list-backend-${{ env.TIMESTAMP }}
          path: target/*.jar  # Adjust if your packaged artifact is not a jar