name: Maven Build and Package

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: subriais/shopping_list_db:1.0.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: shopping_list_db
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          docker pull maven:3.8.4-openjdk-18

      - name: Run Maven inside Docker
        run: |
          docker run --rm \
            --network="host" \ # Uses host network to allow the app to connect to MySQL
            -v "$PWD":/usr/src/mymaven \
            -w /usr/src/mymaven \
            maven:3.8.4-openjdk-18 mvn clean package

      - name: Create a timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Publish package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: shopping-list-backend-${{ env.TIMESTAMP }}
          path: target/*.jar
